POST http://localhost:5254/breakfasts
Content-Type: application/json

{
  "name": "Vegan Sunshine",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal", 
    "Avocado Toast", 
    "Omelette", 
    "Salad"
    ],
  "Sweet": [
    "Cookie"
    ]
}

###

GET http://localhost:5254/Breakfasts/4eca2968-01c1-449c-9262-950fa5164dd7
